# Generated by Django 4.1.4 on 2025-06-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="social_auth_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="social_auth_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("google", "Google"),
                    ("facebook", "Facebook"),
                    ("apple", "Apple"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
