[variables]
PORT = "8000"

[build]
cmd = "pip install -r requirements.txt"

[start]
cmd = "python manage.py migrate --verbosity=2 && python manage.py collectstatic --noinput && gunicorn backend.wsgi --bind 0.0.0.0:$PORT --workers 1 --log-level debug" 