# Generated by Django 4.1.4 on 2025-05-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_parcel_map_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="certification_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="contact_person",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="crop_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="soil_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="unique_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
