# Generated by Django 4.1.4 on 2025-06-19 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_parcel_certification_type_parcel_contact_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parcel",
            name="crop_type",
        ),
    ]
