# Generated by Django 4.1.4 on 2025-04-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_galleryimage_s3_key_galleryimage_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
