# Generated by Django 4.1.4 on 2025-05-03 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("history", "0007_alter_chemicalevent_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="age_of_plants",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="is_outdoor",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="history",
            name="number_of_plants",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productions_operated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="history",
            name="soil_ph",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
