# Generated by Django 4.1.4 on 2025-05-24 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_galleryimage_image_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("history", "0008_history_age_of_plants_history_is_outdoor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoilManagementEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("certified", models.BooleanField(default=False)),
                ("index", models.IntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ST", "Soil Test"),
                            ("PA", "pH Adjustment"),
                            ("OM", "Organic Matter Addition"),
                            ("CC", "Cover Crop"),
                            ("TI", "Tillage"),
                            ("CO", "Composting"),
                        ],
                        default="ST",
                        max_length=2,
                    ),
                ),
                (
                    "soil_ph",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "organic_matter_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("amendment_type", models.CharField(blank=True, max_length=100)),
                ("amendment_amount", models.CharField(blank=True, max_length=100)),
                ("test_results", models.JSONField(blank=True, null=True)),
                (
                    "carbon_sequestration_potential",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.gallery",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_events",
                        to="history.history",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soil Management Event",
                "verbose_name_plural": "Soil Management Events",
            },
        ),
        migrations.CreateModel(
            name="PestManagementEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("certified", models.BooleanField(default=False)),
                ("index", models.IntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SC", "Scouting"),
                            ("BR", "Beneficial Release"),
                            ("TM", "Trap Monitoring"),
                            ("PI", "Pest Identification"),
                            ("TA", "Threshold Assessment"),
                            ("IP", "IPM Implementation"),
                        ],
                        default="SC",
                        max_length=2,
                    ),
                ),
                ("pest_species", models.CharField(blank=True, max_length=200)),
                ("pest_pressure_level", models.CharField(blank=True, max_length=50)),
                ("beneficial_species", models.CharField(blank=True, max_length=200)),
                ("release_quantity", models.CharField(blank=True, max_length=100)),
                ("trap_count", models.IntegerField(blank=True, null=True)),
                (
                    "damage_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("action_threshold_met", models.BooleanField(default=False)),
                ("ipm_strategy", models.TextField(blank=True)),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.gallery",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_events",
                        to="history.history",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pest Management Event",
                "verbose_name_plural": "Pest Management Events",
            },
        ),
        migrations.CreateModel(
            name="EquipmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("certified", models.BooleanField(default=False)),
                ("index", models.IntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MA", "Maintenance"),
                            ("RE", "Repair"),
                            ("CA", "Calibration"),
                            ("FC", "Fuel Consumption"),
                            ("BR", "Breakdown"),
                            ("IN", "Inspection"),
                        ],
                        default="MA",
                        max_length=2,
                    ),
                ),
                ("equipment_name", models.CharField(blank=True, max_length=100)),
                (
                    "fuel_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fuel_type", models.CharField(blank=True, max_length=50)),
                (
                    "maintenance_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "hours_used",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("area_covered", models.CharField(blank=True, max_length=100)),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.gallery",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_events",
                        to="history.history",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Event",
                "verbose_name_plural": "Equipment Events",
            },
        ),
        migrations.CreateModel(
            name="BusinessEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("certified", models.BooleanField(default=False)),
                ("index", models.IntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("HS", "Harvest Sale"),
                            ("CE", "Certification"),
                            ("IN", "Inspection"),
                            ("IS", "Insurance"),
                            ("MA", "Market Analysis"),
                            ("CT", "Contract"),
                            ("CM", "Compliance"),
                        ],
                        default="HS",
                        max_length=2,
                    ),
                ),
                (
                    "revenue_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("quantity_sold", models.CharField(blank=True, max_length=100)),
                ("buyer_name", models.CharField(blank=True, max_length=200)),
                ("certification_type", models.CharField(blank=True, max_length=100)),
                ("inspector_name", models.CharField(blank=True, max_length=200)),
                ("compliance_status", models.CharField(blank=True, max_length=50)),
                (
                    "carbon_credits_earned",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.gallery",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_events",
                        to="history.history",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Event",
                "verbose_name_plural": "Business Events",
            },
        ),
    ]
