# Generated by Django 4.1.4 on 2025-05-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0009_soilmanagementevent_pestmanagementevent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("MN", "Maintenance"),
                    ("RE", "Repair"),
                    ("CA", "Calibration"),
                    ("FC", "Fuel Consumption"),
                    ("BD", "Breakdown"),
                    ("EI", "Inspection"),
                ],
                default="MN",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="weatherevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("FR", "Frost"),
                    ("DR", "Drought"),
                    ("HL", "Hailstorm"),
                    ("HT", "High Temperature"),
                    ("TS", "Tropical Storm"),
                    ("HW", "High Winds"),
                    ("HH", "High Humidity"),
                    ("LH", "Low Humidity"),
                ],
                max_length=2,
            ),
        ),
    ]
