# Generated by Django 4.1.4 on 2025-05-31 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0011_migrate_existing_type_codes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chemicalevent",
            name="certified",
        ),
        migrations.RemoveField(
            model_name="equipmentevent",
            name="certified",
        ),
        migrations.RemoveField(
            model_name="generalevent",
            name="certified",
        ),
        migrations.RemoveField(
            model_name="pestmanagementevent",
            name="certified",
        ),
        migrations.RemoveField(
            model_name="productionevent",
            name="certified",
        ),
        migrations.RemoveField(
            model_name="soilmanagementevent",
            name="certified",
        ),
        migrations.RemoveField(
            model_name="weatherevent",
            name="certified",
        ),
        migrations.DeleteModel(
            name="BusinessEvent",
        ),
    ]
