# Generated by Django 4.1.4 on 2025-06-19 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carbon", "0015_add_crop_types_and_templates"),
        ("history", "0012_remove_chemicalevent_certified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="crop_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Crop type for this production",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productions",
                to="carbon.croptype",
            ),
        ),
    ]
