# Generated by Django 4.1.4 on 2025-06-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0013_add_crop_type_to_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemicalevent",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipmentevent",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generalevent",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pestmanagementevent",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productionevent",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="soilmanagementevent",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
