# Generated by Django 4.1.4 on 2025-06-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_increase_field_lengths'),
        ('history', '0014_add_extra_data_to_events'),
    ]

    operations = [
    ]