# Generated by Django 4.1.4 on 2025-05-04 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0006_establishment_about_establishment_custom_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarbonEmissionSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "unit",
                    models.CharField(
                        help_text="e.g. kg CO2e, liters, kWh", max_length=50
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarbonOffsetAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "unit",
                    models.CharField(
                        help_text="e.g. trees planted, tons CO2 offset", max_length=50
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarbonCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("certifying_body", models.CharField(max_length=100)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="carbon_certifications/"
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carbon_certifications",
                        to="company.establishment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstablishmentCarbonFootprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("amount", models.FloatField(help_text="Amount of emission (in unit)")),
                ("offset_amount", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "emission_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carbon.carbonemissionsource",
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carbon_footprints",
                        to="company.establishment",
                    ),
                ),
                (
                    "offset_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carbon.carbonoffsetaction",
                    ),
                ),
            ],
            options={
                "unique_together": {("establishment", "year", "emission_source")},
            },
        ),
    ]
