# Generated by Django 4.1.4 on 2025-05-04 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0008_history_age_of_plants_history_is_outdoor_and_more"),
        ("company", "0006_establishment_about_establishment_custom_message_and_more"),
        ("carbon", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="establishmentcarbonfootprint",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="carboncertification",
            name="scope",
            field=models.CharField(
                choices=[
                    ("establishment", "Establishment"),
                    ("production", "Production"),
                    ("company", "Company"),
                ],
                default="establishment",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="carboncertification",
            name="verification_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="carbonemissionsource",
            name="category",
            field=models.CharField(
                choices=[
                    ("direct", "Direct Emissions"),
                    ("indirect", "Indirect Emissions"),
                    ("other", "Other"),
                ],
                default="direct",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="carbonoffsetaction",
            name="verification_process",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="carbonoffsetaction",
            name="verification_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="establishmentcarbonfootprint",
            name="production",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carbon_footprints",
                to="history.history",
            ),
        ),
        migrations.AddField(
            model_name="establishmentcarbonfootprint",
            name="verification_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="establishmentcarbonfootprint",
            name="verification_document",
            field=models.FileField(
                blank=True, null=True, upload_to="carbon_verifications/"
            ),
        ),
        migrations.AddField(
            model_name="establishmentcarbonfootprint",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="establishmentcarbonfootprint",
            unique_together={
                ("establishment", "year", "emission_source", "production")
            },
        ),
        migrations.CreateModel(
            name="CarbonReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Report"),
                            ("quarterly", "Quarterly Report"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_emissions", models.FloatField()),
                ("total_offsets", models.FloatField()),
                ("net_carbon", models.FloatField()),
                ("document", models.FileField(upload_to="carbon_reports/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carbon_reports",
                        to="company.establishment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarbonBenchmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("industry", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                ("average_emissions", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
                ("source", models.CharField(max_length=200)),
                ("last_updated", models.DateField(auto_now=True)),
            ],
            options={
                "unique_together": {("industry", "year")},
            },
        ),
    ]
