# Generated by Django 4.1.4 on 2025-05-05 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("history", "0008_history_age_of_plants_history_is_outdoor_and_more"),
        ("company", "0006_establishment_about_establishment_custom_message_and_more"),
        ("carbon", "0002_alter_establishmentcarbonfootprint_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarbonAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("verify", "Verify"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="CarbonEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("year", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("emission", "Emission"), ("offset", "Offset")],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        help_text="Amount in the unit specified by source or offset action"
                    ),
                ),
                (
                    "co2e_amount",
                    models.FloatField(
                        default=0.0, help_text="Calculated CO2 equivalent in kg"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("verified", models.BooleanField(default=False)),
                ("verification_date", models.DateField(blank=True, null=True)),
                (
                    "verification_document",
                    models.FileField(
                        blank=True, null=True, upload_to="carbon_verifications/"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_carbon_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carbon_entries",
                        to="company.establishment",
                    ),
                ),
                (
                    "offset_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carbon.carbonoffsetaction",
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carbon_entries",
                        to="history.history",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarbonSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "unit",
                    models.CharField(
                        help_text="e.g. kg CO2e, liters, kWh", max_length=50
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Emissions"),
                            ("indirect", "Indirect Emissions"),
                            ("other", "Other"),
                        ],
                        default="direct",
                        max_length=50,
                    ),
                ),
                (
                    "default_emission_factor",
                    models.FloatField(
                        default=0.0,
                        help_text="Default kg CO2e per unit for automated calculations",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="establishmentcarbonfootprint",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="establishmentcarbonfootprint",
            name="emission_source",
        ),
        migrations.RemoveField(
            model_name="establishmentcarbonfootprint",
            name="establishment",
        ),
        migrations.RemoveField(
            model_name="establishmentcarbonfootprint",
            name="offset_action",
        ),
        migrations.RemoveField(
            model_name="establishmentcarbonfootprint",
            name="production",
        ),
        migrations.AddField(
            model_name="carbonbenchmark",
            name="company_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="carbonbenchmark",
            name="max_emissions",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="carbonbenchmark",
            name="min_emissions",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="carboncertification",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="carboncertification",
            name="production",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carbon_certifications",
                to="history.history",
            ),
        ),
        migrations.AddField(
            model_name="carboncertification",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="carbonreport",
            name="production",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carbon_reports",
                to="history.history",
            ),
        ),
        migrations.AlterField(
            model_name="carbonreport",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="carbon_reports/"),
        ),
        migrations.DeleteModel(
            name="CarbonEmissionSource",
        ),
        migrations.DeleteModel(
            name="EstablishmentCarbonFootprint",
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="carbon.carbonsource",
            ),
        ),
        migrations.AddField(
            model_name="carbonauditlog",
            name="carbon_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="carbon.carbonentry",
            ),
        ),
        migrations.AddField(
            model_name="carbonauditlog",
            name="certification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="carbon.carboncertification",
            ),
        ),
        migrations.AddField(
            model_name="carbonauditlog",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="carbon.carbonreport",
            ),
        ),
        migrations.AddField(
            model_name="carbonauditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="carbonentry",
            index=models.Index(
                fields=["establishment", "year"], name="carbon_carb_establi_94f035_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carbonentry",
            index=models.Index(
                fields=["production", "year"], name="carbon_carb_product_1710da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carbonentry",
            index=models.Index(fields=["date"], name="carbon_carb_date_b7d945_idx"),
        ),
        migrations.AddIndex(
            model_name="carbonentry",
            index=models.Index(
                fields=["created_at"], name="carbon_carb_created_52306c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="carbonentry",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("establishment__isnull", False), ("production__isnull", True)
                    ),
                    models.Q(
                        ("establishment__isnull", True), ("production__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="either_establishment_or_production",
            ),
        ),
    ]
