# Generated by Django 4.1.4 on 2025-05-17 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("carbon", "0005_greenpoints_microoffset_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarbonOffsetProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("project_type", models.CharField(max_length=100)),
                ("certification_standard", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("price_per_ton", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "available_capacity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CarbonOffsetPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_per_ton", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "certificate_file",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certificate_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carbon.carbonoffsetproject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarbonOffsetCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_number", models.CharField(max_length=100, unique=True)),
                ("verification_code", models.CharField(max_length=100, unique=True)),
                ("certificate_url", models.URLField()),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purchase",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carbon.carbonoffsetpurchase",
                    ),
                ),
            ],
        ),
    ]
