# Generated by Django 4.1.4 on 2025-05-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0006_carbonoffsetproject_carbonoffsetpurchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonentry',
            name='co2e_amount',
            field=models.FloatField(default=0.0, help_text='Amount in CO2 equivalent'),
        ),
    ]
