# Generated by Django 4.1.4 on 2025-05-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_establishment_about_establishment_custom_message_and_more"),
        ("history", "0008_history_age_of_plants_history_is_outdoor_and_more"),
        ("carbon", "0007_carbonentry_co2e_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="sustainabilitybadge",
            name="establishments",
            field=models.ManyToManyField(
                blank=True, related_name="badges", to="company.establishment"
            ),
        ),
        migrations.AddField(
            model_name="sustainabilitybadge",
            name="is_automatic",
            field=models.BooleanField(
                default=False,
                help_text="Whether to automatically award this badge based on score",
            ),
        ),
        migrations.AddField(
            model_name="sustainabilitybadge",
            name="minimum_score",
            field=models.IntegerField(
                default=0,
                help_text="Minimum carbon score to automatically award this badge",
            ),
        ),
        migrations.AddField(
            model_name="sustainabilitybadge",
            name="productions",
            field=models.ManyToManyField(
                blank=True, related_name="badges", to="history.history"
            ),
        ),
    ]
