# Generated by Django 4.1.4 on 2025-05-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon", "0008_sustainabilitybadge_establishments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carbonreport",
            name="document",
            field=models.FileField(
                blank=True,
                help_text="Report document file",
                null=True,
                upload_to="carbon_reports/",
            ),
        ),
    ]
