# Generated by Django 4.1.4 on 2025-05-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon", "0010_add_iot_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="iotdevice",
            name="api_connection_status",
            field=models.CharField(
                choices=[
                    ("connected", "Connected"),
                    ("disconnected", "Disconnected"),
                    ("error", "Connection Error"),
                    ("pending", "Connection Pending"),
                ],
                default="disconnected",
                help_text="Status of API connection",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="iotdevice",
            name="api_error_message",
            field=models.TextField(
                blank=True, help_text="Last API error message if any"
            ),
        ),
        migrations.AddField(
            model_name="iotdevice",
            name="john_deere_machine_id",
            field=models.CharField(
                blank=True,
                help_text="John Deere machine ID for API integration",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="iotdevice",
            name="last_api_sync",
            field=models.DateTimeField(
                blank=True, help_text="Last successful API synchronization", null=True
            ),
        ),
    ]
