# Generated by Django 4.1.4 on 2025-05-31 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carbon", "0011_add_john_deere_integration"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="carbonreport",
            name="carbon_carb_cost_sa_690484_idx",
        ),
        migrations.RemoveField(
            model_name="carbonentry",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="carbonoffsetaction",
            name="cost_per_unit",
        ),
        migrations.RemoveField(
            model_name="carbonreport",
            name="cost_savings",
        ),
        migrations.RemoveField(
            model_name="carbonreport",
            name="recommendations",
        ),
        migrations.RemoveField(
            model_name="carbonsource",
            name="cost_per_unit",
        ),
    ]
