# Generated by Django 4.1.4 on 2025-06-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carbon", "0002_performance_indexes"),
        ("carbon", "0012_remove_carbonreport_carbon_carb_cost_sa_690484_idx_and_more"),
    ]

    operations = []
