# Generated by Django 4.1.4 on 2025-06-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon", "0013_merge_20250610_1221"),
    ]

    operations = [
        migrations.AddField(
            model_name="carbonentry",
            name="data_source",
            field=models.CharField(
                default="Unknown",
                help_text="Source of emission factors (e.g., USDA Agricultural Research Service)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="usda_factors_based",
            field=models.BooleanField(
                default=False,
                help_text="Whether calculations use USDA emission factors",
            ),
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="verification_status",
            field=models.CharField(
                default="estimated",
                help_text="factors_verified, estimated, calculation_error",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="carbonsource",
            name="data_source",
            field=models.CharField(
                default="Unknown",
                help_text="Source of emission factors (e.g., USDA Agricultural Research Service)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="carbonsource",
            name="usda_factors_based",
            field=models.BooleanField(
                default=False,
                help_text="Whether calculations use USDA emission factors",
            ),
        ),
        migrations.AddField(
            model_name="carbonsource",
            name="verification_status",
            field=models.CharField(
                default="estimated",
                help_text="factors_verified, estimated, calculation_error",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="carbonentry",
            index=models.Index(
                fields=["usda_factors_based"], name="carbon_carb_usda_fa_d3807e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carbonentry",
            index=models.Index(
                fields=["verification_status"], name="carbon_carb_verific_3f9a66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carbonsource",
            index=models.Index(
                fields=["usda_factors_based"], name="carbon_carb_usda_fa_bd75d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carbonsource",
            index=models.Index(
                fields=["verification_status"], name="carbon_carb_verific_fa4ec9_idx"
            ),
        ),
    ]
