# Generated by Django 4.1.4 on 2025-06-24 13:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carbon", "0017_add_usda_compliance_models"),
    ]

    operations = [
        # Create VerificationAudit model
        migrations.CreateModel(
            name="VerificationAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("random", "Random Audit"),
                            ("scheduled", "Scheduled Review"),
                            ("complaint", "Complaint Investigation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("auditor_name", models.CharField(max_length=200)),
                ("audit_date", models.DateTimeField()),
                ("findings", models.JSONField(default=dict)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("pending", "Pending Review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("corrective_actions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("carbon_entry", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="verification_audits",
                    to="carbon.carbonentry",
                )),
            ],
            options={
                "db_table": "carbon_verification_audit",
                "ordering": ["-audit_date"],
            },
        ),
        
        # Add missing fields to CarbonEntry (excluding ones that already exist)
        migrations.AddField(
            model_name="carbonentry",
            name="additionality_evidence",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="additionality_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="audit_scheduled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="baseline_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="documentation_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="evidence_requirements_met",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="methodology_template",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="permanence_plan",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="registry_verification_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="third_party_verification_url",
            field=models.URLField(blank=True),
        ),
        
        # Add indexes for new fields
        migrations.AddIndex(
            model_name="carbonentry",
            index=models.Index(
                fields=["additionality_verified"], name="carbon_carb_additio_92e40a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carbonentry",
            index=models.Index(
                fields=["registry_verification_id"],
                name="carbon_carb_registr_3b505b_idx",
            ),
        ),
        
        # Add indexes for VerificationAudit
        migrations.AddIndex(
            model_name="verificationaudit",
            index=models.Index(
                fields=["audit_type"], name="carbon_veri_audit_t_9fda1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationaudit",
            index=models.Index(fields=["result"], name="carbon_veri_result_883718_idx"),
        ),
        migrations.AddIndex(
            model_name="verificationaudit",
            index=models.Index(
                fields=["audit_date"], name="carbon_veri_audit_d_a6a98c_idx"
            ),
        ),
    ]
