# Generated by Django 4.1.4 on 2025-06-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carbon", "0018_add_verification_fields_missing"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE carbon_carbonentry 
            ALTER COLUMN external_verification_id SET DEFAULT '',
            ALTER COLUMN gps_coordinates SET DEFAULT '{}',
            ALTER COLUMN verification_notes SET DEFAULT '',
            ALTER COLUMN baseline_scenario SET DEFAULT '{}',
            ALTER COLUMN detected_patterns SET DEFAULT '{}',
            ALTER COLUMN financial_analysis SET DEFAULT '{}',
            ALTER COLUMN methodology_id SET DEFAULT '',
            ALTER COLUMN monitoring_plan SET DEFAULT '{}',
            ALTER COLUMN registry_name SET DEFAULT '',
            ALTER COLUMN registry_submission_id SET DEFAULT '',
            ALTER COLUMN verification_report_url SET DEFAULT '',
            ALTER COLUMN community_attestations SET DEFAULT '[]';
            """,
            reverse_sql="""
            ALTER TABLE carbon_carbonentry 
            ALTER COLUMN external_verification_id DROP DEFAULT,
            ALTER COLUMN gps_coordinates DROP DEFAULT,
            ALTER COLUMN verification_notes DROP DEFAULT,
            ALTER COLUMN baseline_scenario DROP DEFAULT,
            ALTER COLUMN detected_patterns DROP DEFAULT,
            ALTER COLUMN financial_analysis DROP DEFAULT,
            ALTER COLUMN methodology_id DROP DEFAULT,
            ALTER COLUMN monitoring_plan DROP DEFAULT,
            ALTER COLUMN registry_name DROP DEFAULT,
            ALTER COLUMN registry_submission_id DROP DEFAULT,
            ALTER COLUMN verification_report_url DROP DEFAULT,
            ALTER COLUMN community_attestations DROP DEFAULT;
            """
        ),
    ]
