# Generated by Django 4.1.4 on 2025-06-24 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carbon", "0019_add_default_values_to_required_fields"),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- First, set any NULL values to empty array
            UPDATE carbon_carbonentry 
            SET community_attestations = '[]'::jsonb 
            WHERE community_attestations IS NULL;

            -- Then set the default value
            ALTER TABLE carbon_carbonentry 
            ALTER COLUMN community_attestations SET DEFAULT '[]'::jsonb;
            """,
            reverse_sql="""
            ALTER TABLE carbon_carbonentry 
            ALTER COLUMN community_attestations DROP DEFAULT;
            """
        ),
    ]
