# Generated by Django 4.1.4 on 2025-06-25 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon", "0020_fix_community_attestations_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="carbonentry",
            name="attestation_count",
            field=models.IntegerField(
                default=0, help_text="Number of community attestations received"
            ),
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="audit_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Audit Scheduled"),
                    ("in_progress", "Under Review"),
                    ("passed", "Audit Passed"),
                    ("failed", "Audit Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="community_attestations",
            field=models.JSONField(
                blank=True, default=list, help_text="List of community attestations"
            ),
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="effective_amount",
            field=models.FloatField(
                blank=True, help_text="Amount * trust_score", null=True
            ),
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="evidence_documents",
            field=models.JSONField(
                blank=True, default=list, help_text="List of document URLs as evidence"
            ),
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="evidence_photos",
            field=models.JSONField(
                blank=True, default=list, help_text="List of photo URLs as evidence"
            ),
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="trust_score",
            field=models.FloatField(
                default=0.5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="carbonentry",
            name="verification_level",
            field=models.CharField(
                choices=[
                    ("self_reported", "Self Reported"),
                    ("community_verified", "Community Verified"),
                    ("certified_project", "Certified Project"),
                ],
                default="self_reported",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="carbonauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("verify", "Verify"),
                    ("gaming_detected", "Gaming Detected"),
                    ("audit_scheduled", "Audit Scheduled"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="carbonentry",
            index=models.Index(
                fields=["verification_level"], name="carbon_carb_verific_aa2fb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carbonentry",
            index=models.Index(
                fields=["audit_status"], name="carbon_carb_audit_s_50e3b5_idx"
            ),
        ),
    ]
