# Generated by Django manual migration for MVP optimization
# Removes community verification level and optimizes for 2-tier system

from django.db import migrations, models
import django.core.validators


def convert_community_verified_to_self_reported(apps, schema_editor):
    """Convert existing community_verified entries to self_reported for MVP."""
    CarbonEntry = apps.get_model('carbon', 'CarbonEntry')
    
    # Find all community_verified entries
    community_verified_entries = CarbonEntry.objects.filter(verification_level='community_verified')
    
    # Update them to self_reported and adjust trust scores
    for entry in community_verified_entries:
        entry.verification_level = 'self_reported'
        # Adjust trust score from 0.75 to 0.5 for self_reported
        if entry.trust_score == 0.75:
            entry.trust_score = 0.5
        # Recalculate effective amount based on new trust score
        if entry.effective_amount and entry.amount:
            entry.effective_amount = entry.amount * entry.trust_score
    
    # Bulk update to improve performance
    CarbonEntry.objects.bulk_update(
        community_verified_entries, 
        ['verification_level', 'trust_score', 'effective_amount']
    )


def reverse_migration(apps, schema_editor):
    """Reverse migration - this cannot fully restore community verification data."""
    # We cannot restore the original community verification data
    # as attestations will be lost, so this is intentionally minimal
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('carbon', '0021_carbonentry_attestation_count_and_more'),
    ]

    operations = [
        # First, convert existing community_verified entries to self_reported
        migrations.RunPython(
            convert_community_verified_to_self_reported,
            reverse_migration,
            elidable=True
        ),
        
        # Update the verification_level field choices to remove community_verified
        migrations.AlterField(
            model_name='carbonentry',
            name='verification_level',
            field=models.CharField(
                choices=[
                    ('self_reported', 'Self Reported'),
                    ('certified_project', 'Certified Project'),
                ],
                default='self_reported',
                max_length=25,
            ),
        ),
        
        # Remove community attestation fields as they're no longer needed
        migrations.RemoveField(
            model_name='carbonentry',
            name='community_attestations',
        ),
        
        migrations.RemoveField(
            model_name='carbonentry',
            name='attestation_count',
        ),
    ]