# Generated by Django 4.1.4 on 2025-05-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_company_certifications_company_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="establishment",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="establishment",
            name="custom_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="establishment",
            name="location_highlights",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="establishment",
            name="main_activities",
            field=models.TextField(blank=True, null=True),
        ),
    ]
