# Generated by Django 4.1.4 on 2025-06-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_establishment_about_establishment_custom_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="establishment",
            name="crops_grown",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of crops grown at this establishment",
            ),
        ),
        migrations.AddField(
            model_name="establishment",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Main establishment email",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="establishment",
            name="employee_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of employees", null=True
            ),
        ),
        migrations.AddField(
            model_name="establishment",
            name="establishment_type",
            field=models.CharField(
                blank=True,
                help_text="Type of agricultural operation",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="establishment",
            name="farming_method",
            field=models.CharField(
                blank=True,
                help_text="Primary farming approach",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="establishment",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether the establishment is active"
            ),
        ),
        migrations.AddField(
            model_name="establishment",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Main establishment phone",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="establishment",
            name="sustainability_practices",
            field=models.JSONField(
                blank=True, default=list, help_text="List of sustainability practices"
            ),
        ),
        migrations.AddField(
            model_name="establishment",
            name="total_acreage",
            field=models.FloatField(
                blank=True, help_text="Total land area in acres", null=True
            ),
        ),
        migrations.AddField(
            model_name="establishment",
            name="year_established",
            field=models.PositiveIntegerField(
                blank=True, help_text="Year the establishment was founded", null=True
            ),
        ),
        migrations.AddField(
            model_name="establishment",
            name="zip_code",
            field=models.CharField(
                blank=True, help_text="Postal/ZIP code", max_length=20, null=True
            ),
        ),
    ]
