# Generated by Django 4.1.4 on 2025-06-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_establishment_crops_grown_establishment_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="blockchain_subscription_status",
            field=models.BooleanField(
                default=False,
                help_text="Whether company has active blockchain verification subscription",
            ),
        ),
    ]
