# Generated by Django 4.1.4 on 2025-06-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_add_blockchain_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="employee_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of employees", null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="industry",
            field=models.CharField(
                blank=True,
                help_text="Primary agricultural industry",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether the company is active"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="sustainability_metadata",
            field=models.JSONField(
                blank=True,
                help_text="JSON data containing crop selection, sustainability goals, and carbon benchmarks",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="zip_code",
            field=models.CharField(
                blank=True, help_text="Postal/ZIP code", max_length=20, null=True
            ),
        ),
    ]
