# Generated by Django 4.1.4 on 2025-06-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_increase_field_lengths'),
        ('company', '0009_add_missing_company_fields'),
    ]

    operations = [
    ]