# Generated by Django 4.1.4 on 2025-06-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0010_merge_20250627_2032"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="legal_structure",
            field=models.CharField(
                blank=True,
                help_text="Business legal structure",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="primary_commodities",
            field=models.CharField(
                blank=True,
                help_text="Main agricultural commodities",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="sustainability_commitment",
            field=models.CharField(
                blank=True,
                help_text="Sustainability approach",
                max_length=100,
                null=True,
            ),
        ),
    ]
