# Generated by Django on 2025-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0011_add_agricultural_compliance_fields"),
    ]

    operations = [
        # Remove social media fields from Establishment (moved to Company level)
        migrations.RemoveField(
            model_name="establishment",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="establishment",
            name="instagram",
        ),
        
        # Add operational agricultural fields
        migrations.AddField(
            model_name="establishment",
            name="water_sources",
            field=models.JSONField(
                default=list,
                blank=True,
                help_text="Primary water sources (well, surface water, irrigation district, etc.)"
            ),
        ),
        migrations.AddField(
            model_name="establishment",
            name="climate_zone",
            field=models.CharField(
                max_length=50,
                blank=True,
                null=True,
                help_text="Climate zone or growing region classification"
            ),
        ),
        migrations.AddField(
            model_name="establishment",
            name="soil_types",
            field=models.JSONField(
                default=list,
                blank=True,
                help_text="Primary soil types present on the establishment"
            ),
        ),
        migrations.AddField(
            model_name="establishment",
            name="conservation_practices",
            field=models.JSONField(
                default=list,
                blank=True,
                help_text="Conservation practices implemented (cover crops, buffer strips, etc.)"
            ),
        ),
        migrations.AddField(
            model_name="establishment",
            name="irrigation_methods",
            field=models.JSONField(
                default=list,
                blank=True,
                help_text="Irrigation methods used (drip, sprinkler, flood, etc.)"
            ),
        ),
    ]